version: '3.4'

services:
  front:
    image: front
    build:
      context: front-login-v2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      TIMEOUT: 120000
      RECOGNITION_APIKEY: 44334fea-f12a-4e65-974b-06c8b35ed27a
      RECOGNITION_API: http://localhost:8000/api/v1/recognition/
      VERIFICATION_APIKEY: d339e07a-e9a8-4419-a67c-3beb8461897d
      VERIFICATION_API: http://localhost:8000/api/v1/verification/
      OCR_API: http://api:8200/ocr
      NIVEL_REC: '0.8'
    ports:
      - 5001:5001
  api:
    image: api
    build:
      context: ocr-tesseract
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - 8200
    networks:
      default:
        aliases:
          - api
